// Prints SQL that fills an empty database with the default content from
// src/lib/cms/seed.ts. Existing rows are left alone, so it is safe to re-run.
//   npm run seed:sql > supabase/seed.sql   (then run it in the SQL editor)
import { seedPages, seedPosts, seedProjects, seedSections, seedServices, seedSettings } from '../src/lib/cms/seed.ts'

const lit = (v: unknown): string => {
  if (v === null || v === undefined) return 'null'
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  if (typeof v === 'string') return `'${v.replace(/'/g, "''")}'`
  return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
}
const insert = (table: string, rows: Record<string, unknown>[], conflict: string) => {
  if (!rows.length) return ''
  const cols = Object.keys(rows[0])
  const values = rows.map((r) => `  (${cols.map((c) => lit(r[c])).join(', ')})`).join(',\n')
  return `insert into public.${table} (${cols.join(', ')}) values\n${values}\non conflict (${conflict}) do nothing;\n`
}
const omitId = <T extends { id: string }>({ id: _id, ...rest }: T) => rest

const out = [
  '-- Default content (generated by scripts/seed-sql.ts)',
  'begin;',
  insert('settings', [{ id: 'site', data: seedSettings }], 'id'),
  insert('pages', seedPages, 'slug'),
  insert('sections', seedSections.map(omitId), 'page_slug, key'),
  insert('services', seedServices.map(omitId), 'slug'),
  insert('projects', seedProjects.map(omitId), 'slug'),
  insert('posts', seedPosts.map(omitId), 'slug'),
  'commit;',
]
console.log(out.join('\n'))
