-- Default content (generated by scripts/seed-sql.ts)
begin;
insert into public.settings (id, data) values
  ('site', '{"brand":{"name":"nova","tagline":"Digital 360: software, product and growth, all in one studio."},"seo":{"title":"Nova Studio · Digital 360 agency","description":"Nova Studio designs, builds and grows digital products: websites, web software, e-commerce, mobile apps, SEO, marketing and AI automation."},"contact":{"email":"hello@example.com","phone":"+91 90000 00000","address":"Your studio address, City, India","mapUrl":"https://maps.google.com","hours":"Mon–Sat · 10:00–19:00 IST"},"nav":[{"label":"Home","href":"/"},{"label":"Services","href":"/services"},{"label":"Projects","href":"/projects"},{"label":"Blog","href":"/blog"},{"label":"Contact","href":"/contact"}],"cta":{"label":"Get a quote","href":"/quote"},"dock":{"menuLabel":"Menu","cta":{"label":"get my product","href":"/quote"},"secondary":{"label":"Cases","href":"/projects"}},"socials":[{"label":"in","href":"https://www.linkedin.com"},{"label":"gh","href":"https://github.com"},{"label":"ig","href":"https://www.instagram.com"},{"label":"x","href":"https://x.com"}],"footer":{"word":"nova","pronunciation":"[noh-vuh] noun • latin","definition":"The word *nova* derives from the Latin word *novus* meaning \"new\": a star that suddenly shines brighter than ever before.","credit":"Developed and designed by Nova Studio, 2026. All rights reserved.","badge":"LET''S\nBUILD","legal":[{"label":"Terms","href":"/blog"},{"label":"Privacy Policy","href":"/blog"},{"label":"Cookie policy","href":"/blog"}]},"transitionWords":["CODE","SPEED","SCALE"],"loader":{"enabled":true,"text":"loading good vibes"},"detailCta":{"title":"HAVE A PROJECT\nIN MIND?","button":{"label":"get a quote","href":"/quote"}}}'::jsonb)
on conflict (id) do nothing;

insert into public.pages (slug, title, seo_title, seo_description, og_image) values
  ('home', 'Home', null, null, null),
  ('services', 'Services', 'Services · Nova Studio', 'Nine ways we help brands grow in digital, from corporate websites to AI agents.', null),
  ('projects', 'Projects', 'Projects · Nova Studio', 'Selected websites, software, stores and apps we designed and built.', null),
  ('blog', 'Blog', 'Blog · Nova Studio', 'Notes on design, engineering, SEO and growth from the Nova team.', null),
  ('contact', 'Contact', 'Contact · Nova Studio', 'Tell us about your project. We reply within 24 hours.', null),
  ('quote', 'Get a quote', 'Get a quote · Nova Studio', 'Pick the services you need, share a budget and get a fixed quote.', null)
on conflict (slug) do nothing;

insert into public.sections (page_slug, key, type, label, position, visible, data) values
  ('home', 'hero', 'hero', 'Hero', 0, true, '{"tag":"New name, same\nengineering DNA","line1":"Y{O|wide}UR","words":[{"text":"DIGITAL 360"},{"text":"SOFTWARE"},{"text":"PRODUCT"},{"text":"ALL-IN-ONE"}],"line3":"AGEN{c}Y","badge":{"label":"LET''S\nBUILD","href":"/quote"}}'::jsonb),
  ('home', 'manifesto', 'manifesto', 'Manifesto (curved text)', 1, true, '{"label":"OUR MANIFESTO","curveText":"THE CODE BEHIND BRAND SUCCESS ✺","paragraph":"We bring strategy, engineering, and an agile approach together to help brands connect with people, and turn that connection into real results."}'::jsonb),
  ('home', 'story', 'story', 'Icon story', 2, true, '{"title":"WE ENGINEER PRODUCTS AND PLATFORMS THAT SCALE","text":"Clean in code. Sharp in function. Across our client projects: load times down 63%, release cycles 4× faster, 99.98% uptime after launch.","lines":[{"text":"We {b|script}uild products [crown] people love"},{"text":"and software [heart] that wins clients."},{"text":"Cl{e}an in code. [bolt]"},{"text":"Sharp in [cursor][chart] function."}]}'::jsonb),
  ('home', 'clients', 'connection', 'Clients (coil + rating)', 3, true, '{"label":"OUR CLIENTS","line1":"WHEN THE","word":"CONNECTION","line3":"IS REAL, IT SHOWS","rating":"9.6","ratingText":"OVERALL CLIENT RATING SCORE ·","logos":[{"name":"zenith"},{"name":"KITE"},{"name":"OrbitPay"},{"name":"UMBRA"},{"name":"pulse+"},{"name":"Northwind"},{"name":"BLOOM"},{"name":"volt"}]}'::jsonb),
  ('home', 'services-head', 'heading', 'Services heading', 4, true, '{"title":"WHAT ARE WE\nBUILDING FOR\nYOU?"}'::jsonb),
  ('home', 'service-cards', 'serviceCards', 'Service cards (3D flip)', 5, true, '{"cards":[{"title":"PRODUCT\nDESIGN","tone":"lime","text":"Interfaces that convert. Clear flows that make the next step obvious. Less hesitation. More forward movement.","button":{"label":"design my product","href":"/services/corporate-web-design"}},{"title":"WEB & APP\nENGINEERING","tone":"orange","text":"Speed you can feel: fast loading, rock-solid APIs, tests built in. Your product just works, and quietly earns trust.","button":{"label":"build my product","href":"/services/web-software-apps"}},{"title":"CUSTOM\nSOFTWARE?","tone":"blue","text":"When things don''t fit templates (SaaS, platform, marketplace or internal tools) we turn complexity into clarity.","button":{"label":"discuss my project","href":"/quote"}}]}'::jsonb),
  ('home', 'tech-stack', 'logoBand', 'Tech stack marquee', 6, true, '{"label":"OUR TECH STACK","tone":"lime","direction":"left","items":[{"name":"JavaScript","icon":"javascript"},{"name":"TypeScript","icon":"typescript"},{"name":"React","icon":"react"},{"name":"Next.js","icon":"nextdotjs"},{"name":"Node.js","icon":"nodedotjs"},{"name":"Supabase","icon":"supabase"},{"name":"PostgreSQL","icon":"postgresql"},{"name":"Tailwind CSS","icon":"tailwindcss"},{"name":"GSAP","icon":"gsap"},{"name":"Flutter","icon":"flutter"},{"name":"Figma","icon":"figma"},{"name":"Docker","icon":"docker"},{"name":"VS Code"},{"name":"Cursor","icon":"cursor"},{"name":"Claude","icon":"claude"},{"name":"Codex"},{"name":"GitHub Copilot","icon":"githubcopilot"},{"name":"Vercel","icon":"vercel"}]}'::jsonb),
  ('home', 'cases', 'cases', 'Case carousel', 7, true, '{"limit":11}'::jsonb),
  ('home', 'signposts', 'signposts', 'Signposts', 8, true, '{"primary":{"label":"VIEW ALL CA{S}ES","href":"/projects"},"secondary":{"label":"VIEW ALL BLOGS","href":"/blog"}}'::jsonb),
  ('home', 'bond', 'bond', 'Two-circle reveal', 9, true, '{"title":"NICE TO\nBUILD\nWITH YOU"}'::jsonb),
  ('home', 'about', 'about', 'About (word fill)', 10, true, '{"label":"ABOUT US","paragraph":"We''re thinkers, makers, and coders, coffee lovers (mostly all), bug hunters, curious by nature, pragmatic by choice. We explore, question, and ship until the answer fits. Every project is a journey, and we''re here for the ride.","link":{"label":"BUILD MORE WITH US","href":"/contact"},"photos":[]}'::jsonb),
  ('home', 'process', 'process', 'Process', 11, true, '{"label":"HOW WE WORK","title":"FROM IDEA\nTO LAUNCH","steps":[{"title":"Discovery","duration":"1–2 weeks","text":"We learn your business, users and goals, audit what exists and agree on scope, budget and success metrics."},{"title":"Design","duration":"1–2 weeks","text":"Wireframes, then high-fidelity screens and a clickable prototype. You approve every screen before we write code."},{"title":"Development","duration":"2–3 weeks","text":"Clean, tested code in short sprints with a live staging link, so you see progress every few days."},{"title":"Launch","duration":"1 week","text":"Performance, SEO and security checks, analytics, go-live and a handover session for your team."},{"title":"Support","duration":"Ongoing","text":"Monitoring, updates, backups and new features on a monthly plan, with a 24-hour response time."}]}'::jsonb),
  ('home', 'audit', 'audit', 'Free audit', 12, true, '{"title":"{G|g}ET A FREE\nAUDIT OF YOUR\nPRODUC{T|slant}","chips":[{"label":"Speed","value":99,"tone":"sky"},{"label":"SEO","value":100,"tone":"orange"},{"label":"Security","value":94,"tone":"yellow"},{"label":"Code quality","value":82,"tone":"violet"},{"label":"Accessibility","value":89,"tone":"lime"}],"cta":{"label":"get my free audit","href":"/quote?service=seo-performance"}}'::jsonb),
  ('home', 'mood', 'mood', 'Mood picker', 13, true, '{"title":"SO… HOW {D|slant}O\nWE MAKE YOU FEEL?","sub":"Choose your vibe, we''re listening.","options":[{"label":"Just looking","ring":"JUST LOOKING · NOT RIGHT NOW · JUST LOOKING · NOT RIGHT NOW ·","cta":"keep me posted","href":"/blog"},{"label":"I want a product","ring":"I WANT A PRODUCT · I WANT A PRODUCT · I WANT A PRODUCT ·","cta":"get my product","href":"/quote"},{"label":"I want a free audit","ring":"I WANT A FREE AUDIT · I WANT A FREE AUDIT · I WANT A FREE AUDIT ·","cta":"get my free audit","href":"/quote?service=seo-performance"}]}'::jsonb),
  ('home', 'partners', 'logoBand', 'Partners marquee', 14, true, '{"label":"OUR PARTNERS","tone":"blue","direction":"right","items":[{"name":"Razorpay","icon":"razorpay"},{"name":"Shiprocket"},{"name":"Shopify","icon":"shopify"},{"name":"WordPress","icon":"wordpress"},{"name":"WooCommerce","icon":"woocommerce"},{"name":"Stripe","icon":"stripe"},{"name":"PayPal","icon":"paypal"},{"name":"Google","icon":"google"},{"name":"Meta","icon":"meta"},{"name":"Cloudflare","icon":"cloudflare"},{"name":"Zoho","icon":"zoho"},{"name":"HubSpot","icon":"hubspot"},{"name":"WhatsApp","icon":"whatsapp"},{"name":"Mailchimp","icon":"mailchimp"}]}'::jsonb),
  ('home', 'marquee', 'marquee', 'Name marquee', 15, true, '{"text":"NOVA"}'::jsonb),
  ('services', 'hero', 'pageHero', 'Page hero', 0, true, '{"eyebrow":"SERVICES","title":"WE GROW\nYOUR BRAND\nIN DIGIT{A}L","text":"Nine services, one team. Pick one, or let us run your whole digital 360: from the first pixel to the thousandth customer."}'::jsonb),
  ('services', 'list', 'servicesList', 'Services list', 1, true, '{"label":"WHAT WE DO","title":"NINE WAYS\nWE HELP"}'::jsonb),
  ('services', 'process', 'process', 'Process', 2, true, '{"label":"HOW WE WORK","title":"FROM IDEA\nTO LAUNCH","steps":[{"title":"Discovery","duration":"1–2 weeks","text":"We learn your business, users and goals, audit what exists and agree on scope, budget and success metrics."},{"title":"Design","duration":"1–2 weeks","text":"Wireframes, then high-fidelity screens and a clickable prototype. You approve every screen before we write code."},{"title":"Development","duration":"2–3 weeks","text":"Clean, tested code in short sprints with a live staging link, so you see progress every few days."},{"title":"Launch","duration":"1 week","text":"Performance, SEO and security checks, analytics, go-live and a handover session for your team."},{"title":"Support","duration":"Ongoing","text":"Monitoring, updates, backups and new features on a monthly plan, with a 24-hour response time."}]}'::jsonb),
  ('services', 'cta', 'ctaBand', 'Call to action', 3, true, '{"title":"LET''S BUILD\nSOMETHING GREAT","text":"Tell us where you want to be in six months. We will map the fastest way there, with a fixed quote.","button":{"label":"get a quote","href":"/quote"}}'::jsonb),
  ('projects', 'hero', 'pageHero', 'Page hero', 0, true, '{"eyebrow":"PROJECTS","title":"WORK WE''RE\nPR{O|wide}UD OF","text":"Corporate sites, software, stores and apps, built for brands that wanted more than a template."}'::jsonb),
  ('projects', 'grid', 'projectsGrid', 'Projects grid', 1, true, '{"label":"SELECTED WORK","allLabel":"All"}'::jsonb),
  ('projects', 'cta', 'ctaBand', 'Call to action', 2, true, '{"title":"LET''S BUILD\nSOMETHING GREAT","text":"Tell us where you want to be in six months. We will map the fastest way there, with a fixed quote.","button":{"label":"get a quote","href":"/quote"}}'::jsonb),
  ('blog', 'hero', 'pageHero', 'Page hero', 0, true, '{"eyebrow":"BLOG","title":"NOTES FROM\nTHE ST{U}DIO","text":"What we learn building websites, software and growth engines, written down so you can use it too."}'::jsonb),
  ('blog', 'grid', 'postsGrid', 'Posts grid', 1, true, '{"label":"LATEST POSTS","empty":"New posts are on the way."}'::jsonb),
  ('blog', 'cta', 'ctaBand', 'Call to action', 2, true, '{"title":"LET''S BUILD\nSOMETHING GREAT","text":"Tell us where you want to be in six months. We will map the fastest way there, with a fixed quote.","button":{"label":"get a quote","href":"/quote"}}'::jsonb),
  ('contact', 'hero', 'pageHero', 'Page hero', 0, true, '{"eyebrow":"CONTACT","title":"LET''S TALK\nAB{O|wide}UT IT","text":"A new website, an app, or a second opinion on what you already have: tell us, we reply within 24 hours."}'::jsonb),
  ('contact', 'form', 'contact', 'Contact details + form', 1, true, '{"title":"SAY HELLO","text":"Prefer email or a call? Use the details below, or send the form and we will get back to you.","formTitle":"SEND A MESSAGE","success":"Thanks! Your message is in. We will reply within 24 hours."}'::jsonb),
  ('contact', 'marquee', 'marquee', 'Name marquee', 2, true, '{"text":"NOVA"}'::jsonb),
  ('quote', 'hero', 'pageHero', 'Page hero', 0, true, '{"eyebrow":"GET A QUOTE","title":"TELL US WHAT\nY{O|wide}U NEED","text":"Pick the services, share a budget and a timeline. We send a fixed quote within two working days."}'::jsonb),
  ('quote', 'form', 'quote', 'Quote form', 1, true, '{"title":"YOUR PROJECT","text":"The more you tell us, the sharper the quote. Nothing here is binding.","budgets":[{"text":"Under ₹50k"},{"text":"₹50k – ₹2L"},{"text":"₹2L – ₹5L"},{"text":"₹5L – ₹10L"},{"text":"₹10L+"},{"text":"Not sure yet"}],"timelines":[{"text":"ASAP"},{"text":"1–2 months"},{"text":"3–6 months"},{"text":"Flexible"}],"success":"Thanks! We have your brief and will send a quote within two working days."}'::jsonb)
on conflict (page_slug, key) do nothing;

insert into public.services (published, cover_url, seo_title, seo_description, slug, position, color, title, summary, body, features, deliverables) values
  (true, null, null, null, 'corporate-web-design', 0, 'orange', 'Corporate web design', 'Fast, beautiful company websites that explain what you do in five seconds and turn visitors into enquiries.', 'Your website is often the first meeting with a client. We design and build corporate sites that feel premium, load instantly and are easy for your team to update.

Every site comes with a content management system, SEO foundations and analytics, so it keeps working after launch.', '[{"title":"Custom design","text":"No templates. A look built around your brand and your buyers."},{"title":"Editable content","text":"Update every text, image and page yourself, no developer needed."},{"title":"Motion that guides","text":"Tasteful animation that draws the eye to what matters."},{"title":"SEO ready","text":"Clean markup, fast pages and structured data from day one."}]'::jsonb, '[{"text":"Brand-aligned UI design"},{"text":"Responsive website"},{"text":"CMS with page sections"},{"text":"Analytics and SEO setup"},{"text":"Training session"}]'::jsonb),
  (true, null, null, null, 'web-software-apps', 1, 'blue', 'Web software & apps', 'Dashboards, portals, SaaS products and internal tools, engineered to scale and pleasant to use.', 'When a spreadsheet or an off-the-shelf tool stops being enough, we build the software your business actually needs.

We plan the data model with you, design the flows, and ship in short sprints with a live staging link.', '[{"title":"Product thinking","text":"We challenge scope so you launch sooner with what matters."},{"title":"Solid architecture","text":"Typed code, tests and a database designed for growth."},{"title":"Roles and security","text":"Sign-in, permissions and audit trails done properly."},{"title":"Integrations","text":"Payments, email, CRMs, ERPs and any API you use."}]'::jsonb, '[{"text":"Product scope and roadmap"},{"text":"UX flows and UI design"},{"text":"Web application"},{"text":"Admin panel"},{"text":"Documentation and handover"}]'::jsonb),
  (true, null, null, null, 'e-commerce', 2, 'lime', 'E-commerce', 'Online stores on Shopify, WooCommerce or custom stacks, with payments, shipping and marketing wired in.', 'We build stores that sell: quick product pages, a checkout without friction, and the back-office tools you need to run it.

Payments with Razorpay or Stripe, shipping with Shiprocket, and marketing pixels are set up and tested before launch.', '[{"title":"Conversion-first UX","text":"Product pages and checkout designed around buying."},{"title":"Payments and shipping","text":"Razorpay, Stripe, PayPal, Shiprocket and more."},{"title":"Catalogue tools","text":"Bulk import, variants, stock and discounts."},{"title":"Growth ready","text":"Pixels, feeds and email flows from day one."}]'::jsonb, '[{"text":"Store design"},{"text":"Shopify, WooCommerce or custom build"},{"text":"Payment and shipping setup"},{"text":"Product import"},{"text":"Launch checklist"}]'::jsonb),
  (true, null, null, null, 'seo-performance', 3, 'sky', 'SEO & performance', 'Technical SEO, content structure and Core Web Vitals work that moves you up the results page.', 'Rankings follow speed, structure and useful content. We audit your site, fix what slows it down, and build a plan for the searches your buyers make.

You get a clear report every month, in plain language.', '[{"title":"Technical audit","text":"Crawl, indexation, schema and site speed checked in depth."},{"title":"Core Web Vitals","text":"We make pages load and respond instantly."},{"title":"Content plan","text":"Topics and pages mapped to real search demand."},{"title":"Local SEO","text":"Google Business Profile and local listings tuned."}]'::jsonb, '[{"text":"Free audit report"},{"text":"Speed optimisation"},{"text":"Keyword and content map"},{"text":"Schema markup"},{"text":"Monthly reporting"}]'::jsonb),
  (true, null, null, null, 'management-maintenance', 4, 'violet', 'Management & maintenance', 'Updates, backups, monitoring and small improvements every month, so your site never falls behind.', 'Websites and apps need care. We keep yours secure, fast and up to date, and handle the small changes your team needs.

Every plan includes uptime monitoring and a 24-hour response time.', '[{"title":"Security updates","text":"Frameworks, plugins and servers kept patched."},{"title":"Backups","text":"Daily backups with tested restores."},{"title":"Monitoring","text":"Uptime and error alerts go straight to us."},{"title":"Change hours","text":"Monthly hours for content and feature tweaks."}]'::jsonb, '[{"text":"Monthly maintenance plan"},{"text":"Uptime monitoring"},{"text":"Backups"},{"text":"Priority support"},{"text":"Monthly health report"}]'::jsonb),
  (true, null, null, null, 'business-automation', 5, 'yellow', 'Business automation', 'Connect your tools and remove repetitive work: leads, invoices, reports and approvals that run themselves.', 'Most teams lose hours a week copying data between apps. We map your processes and automate them with n8n, Zapier or custom code.

The result: fewer mistakes, faster responses and a team focused on real work.', '[{"title":"Process mapping","text":"We find the tasks worth automating first."},{"title":"Tool integrations","text":"CRMs, sheets, accounting, WhatsApp and email."},{"title":"Custom workflows","text":"n8n, Zapier or code, whatever fits best."},{"title":"Dashboards","text":"Live numbers instead of weekly spreadsheets."}]'::jsonb, '[{"text":"Automation audit"},{"text":"Workflow build"},{"text":"Integrations"},{"text":"Reporting dashboard"},{"text":"Team training"}]'::jsonb),
  (true, null, null, null, 'digital-marketing', 6, 'pink', 'Digital marketing', 'Performance ads, social media and email campaigns measured against one thing: revenue.', 'We plan, launch and optimise campaigns on Google, Meta and email, with tracking you can trust.

Creative, landing pages and analytics come from the same team, so nothing gets lost between agencies.', '[{"title":"Paid ads","text":"Google and Meta campaigns tuned every week."},{"title":"Social media","text":"Content calendars and creatives that fit your brand."},{"title":"Email and WhatsApp","text":"Automated flows that bring customers back."},{"title":"Tracking","text":"Pixels, conversions and dashboards set up correctly."}]'::jsonb, '[{"text":"Marketing plan"},{"text":"Ad campaigns"},{"text":"Landing pages"},{"text":"Creative assets"},{"text":"Monthly performance report"}]'::jsonb),
  (true, null, null, null, 'mobile-apps', 7, 'red', 'Mobile apps', 'iOS and Android apps with React Native or Flutter, from prototype to the App Store and Play Store.', 'We design and build mobile apps that feel native, work offline and are a joy to use.

One codebase for both platforms keeps costs down, and we handle store submission and updates.', '[{"title":"Cross-platform","text":"React Native or Flutter for iOS and Android."},{"title":"Native feel","text":"Smooth gestures, notifications and offline mode."},{"title":"Backend included","text":"APIs, auth and an admin panel to run the app."},{"title":"Store launch","text":"Listings, screenshots and review handled for you."}]'::jsonb, '[{"text":"App design"},{"text":"iOS and Android app"},{"text":"Backend and admin"},{"text":"Store submission"},{"text":"Analytics and crash reporting"}]'::jsonb),
  (true, null, null, null, 'ai-agents-automation', 8, 'ink', 'AI agents & automation', 'AI assistants, chatbots and agents built on Claude and other models, connected to your data and tools.', 'AI is useful when it is connected to your real work. We build assistants that answer customers, agents that handle back-office tasks, and search over your own documents.

We start with one measurable use case, prove it, then expand.', '[{"title":"Support assistants","text":"Answer customers on your site and WhatsApp, around the clock."},{"title":"Internal agents","text":"Draft, summarise, classify and update records for your team."},{"title":"Knowledge search","text":"Ask questions over your documents and data."},{"title":"Safe by design","text":"Guardrails, human review and clear logs."}]'::jsonb, '[{"text":"Use-case workshop"},{"text":"AI agent or assistant"},{"text":"Tool and data integrations"},{"text":"Evaluation and guardrails"},{"text":"Usage dashboard"}]'::jsonb)
on conflict (slug) do nothing;

insert into public.projects (slug, name, client, category, service_slug, year, url, color, cover_url, gallery, summary, body, quote, quote_author, rating, results, tags, featured, position, published, seo_title, seo_description) values
  ('zenith', 'ZENITH', 'Zenith Fitness', 'Mobile', 'mobile-apps', 2026, null, 'lime', null, '[]'::jsonb, 'Zenith Fitness came to us for mobile app. We planned, designed and shipped it end to end.', '## The brief

Zenith Fitness needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> They shipped our app in eight weeks and it has not gone down once.', 'They shipped our app in eight weeks and it has not gone down once.', 'Zenith Fitness', 4.9, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"MOBILE APP"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 0, true, null, null),
  ('kite', 'KITE', 'Kite Travel', 'Software', 'web-software-apps', 2026, null, 'blue', null, '[]'::jsonb, 'Kite Travel came to us for web platform. We planned, designed and shipped it end to end.', '## The brief

Kite Travel needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> Clear process, honest estimates and a product our users love.', 'Clear process, honest estimates and a product our users love.', 'Kite Travel', 5, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"WEB PLATFORM"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 1, true, null, null),
  ('orbitpay', 'ORBITPAY', 'OrbitPay', 'Software', 'web-software-apps', 2025, null, 'orange', null, '[]'::jsonb, 'OrbitPay came to us for fintech api. We planned, designed and shipped it end to end.', '## The brief

OrbitPay needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> Security-first engineering. Our audit passed on the first try.', 'Security-first engineering. Our audit passed on the first try.', 'OrbitPay', 4.9, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"FINTECH API"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 2, true, null, null),
  ('umbra', 'UMBRA', 'Umbra Studio', 'Corporate', 'corporate-web-design', 2025, null, 'lime', null, '[]'::jsonb, 'Umbra Studio came to us for corporate website. We planned, designed and shipped it end to end.', '## The brief

Umbra Studio needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> Our new site finally feels as good as the work we do.', 'Our new site finally feels as good as the work we do.', 'Umbra Studio', 5, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"CORPORATE WEBSITE"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 3, true, null, null),
  ('lumen-labs', 'LUMEN LABS', 'Lumen Labs', 'Software', 'ai-agents-automation', 2026, null, 'blue', null, '[]'::jsonb, 'Lumen Labs came to us for ai agent. We planned, designed and shipped it end to end.', '## The brief

Lumen Labs needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> Their support agent answers 70% of our tickets before a human needs to.', 'Their support agent answers 70% of our tickets before a human needs to.', 'Lumen Labs', 4.9, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"AI AGENT"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 4, true, null, null),
  ('northwind', 'NORTHWIND', 'Northwind', 'Automation', 'business-automation', 2025, null, 'orange', null, '[]'::jsonb, 'Northwind came to us for business automation. We planned, designed and shipped it end to end.', '## The brief

Northwind needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> They helped us structure the process before writing any code. We save 30 hours a week.', 'They helped us structure the process before writing any code. We save 30 hours a week.', 'Northwind', 5, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"BUSINESS AUTOMATION"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 5, true, null, null),
  ('pulse-health', 'PULSE HEALTH', 'Pulse Health', 'Corporate', 'seo-performance', 2025, null, 'lime', null, '[]'::jsonb, 'Pulse Health came to us for seo & performance. We planned, designed and shipped it end to end.', '## The brief

Pulse Health needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> Organic traffic tripled in six months. Accessible, compliant and fast.', 'Organic traffic tripled in six months. Accessible, compliant and fast.', 'Pulse Health', 4.8, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"SEO & PERFORMANCE"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 6, true, null, null),
  ('ferry', 'FERRY', 'Ferry Logistics', 'Software', 'web-software-apps', 2024, null, 'blue', null, '[]'::jsonb, 'Ferry Logistics came to us for marketplace. We planned, designed and shipped it end to end.', '## The brief

Ferry Logistics needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> Bookings doubled in the first quarter after launch.', 'Bookings doubled in the first quarter after launch.', 'Ferry Logistics', 4.9, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"MARKETPLACE"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 7, true, null, null),
  ('bloom', 'BLOOM', 'Bloom Market', 'E-Commerce', 'e-commerce', 2026, null, 'orange', null, '[]'::jsonb, 'Bloom Market came to us for shopify store. We planned, designed and shipped it end to end.', '## The brief

Bloom Market needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> Page speed went from painful to instant, and so did our checkout.', 'Page speed went from painful to instant, and so did our checkout.', 'Bloom Market', 5, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"SHOPIFY STORE"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 8, true, null, null),
  ('volt', 'VOLT', 'Volt Energy', 'Marketing', 'digital-marketing', 2024, null, 'lime', null, '[]'::jsonb, 'Volt Energy came to us for digital marketing. We planned, designed and shipped it end to end.', '## The brief

Volt Energy needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> Cost per lead down 42% while volume went up.', 'Cost per lead down 42% while volume went up.', 'Volt Energy', 4.9, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"DIGITAL MARKETING"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 9, true, null, null),
  ('harbor', 'HARBOR', 'Harbor CRM', 'E-Commerce', 'management-maintenance', 2024, null, 'blue', null, '[]'::jsonb, 'Harbor CRM came to us for maintenance. We planned, designed and shipped it end to end.', '## The brief

Harbor CRM needed a partner who could move fast without cutting corners.

## What we did

Discovery workshops, a clickable prototype, then weekly releases to a staging link until launch day.

## The result

> Zero downtime in two years. We forget the site even needs care.', 'Zero downtime in two years. We forget the site even needs care.', 'Harbor CRM', 4.9, '[{"value":"63%","label":"faster load times"},{"value":"4×","label":"quicker releases"},{"value":"99.98%","label":"uptime after launch"}]'::jsonb, '[{"text":"MAINTENANCE"},{"text":"DESIGN"},{"text":"ENGINEERING"}]'::jsonb, true, 10, true, null, null)
on conflict (slug) do nothing;

insert into public.posts (slug, title, excerpt, body, cover_url, tags, author, read_minutes, published_at, published, seo_title, seo_description) values
  ('why-website-speed-wins-clients', 'Why website speed quietly wins you clients', 'Every second of load time costs enquiries. Here is what actually makes a site fast, and what to fix first.', 'A slow site does not look broken, it just loses people.

## What to measure

Look at **Largest Contentful Paint**, **Interaction to Next Paint** and **Cumulative Layout Shift**. Google uses all three.

## What to fix first

1. Oversized images
2. Render-blocking fonts and scripts
3. Slow hosting and no caching

Fix those and most sites get twice as fast in a week.', null, '[{"text":"PERFORMANCE"},{"text":"SEO"}]'::jsonb, 'Nova Studio', 4, '2026-09-01T09:00:00Z', true, null, null),
  ('ai-agents-for-small-teams', 'AI agents for small teams: where to start', 'Skip the hype. Pick one repetitive task, measure it, automate it. A practical guide.', 'The best first AI project is boring: a task your team repeats every day.

## Good first use cases

- Answering common customer questions
- Summarising calls and emails
- Sorting and tagging incoming leads

## Keep a human in the loop

Start with drafts a person approves. When the drafts are reliably good, let the agent act on its own.', null, '[{"text":"AI"},{"text":"AUTOMATION"}]'::jsonb, 'Nova Studio', 5, '2026-08-20T09:00:00Z', true, null, null),
  ('shopify-or-custom-store', 'Shopify, WooCommerce or custom: choosing your store', 'Each option fits a different stage of growth. How to choose without regretting it a year later.', '## Shopify

Fastest to launch, great apps, monthly fees.

## WooCommerce

Flexible and familiar if you already run WordPress.

## Custom

When your catalogue, pricing or checkout does not fit a template.

Not sure? Ask us for a free audit and we will recommend one in writing.', null, '[{"text":"E-COMMERCE"}]'::jsonb, 'Nova Studio', 3, '2026-08-05T09:00:00Z', true, null, null)
on conflict (slug) do nothing;

commit;
